apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
  - port: 443 #service暴露在cluster ip上的端口，通过<cluster ip>:port访问服务
    targetPort: 443 #Pod的外部访问端口，port和nodePort的数据通过这个端口进入到Pod内部，Pod里面的containers的端口映射到这个端口，提供服务
  clusterIP: 20.1.0.2
  selector:
    app: admission-webhook
